import argparse
import subprocess
import sys
from datetime import datetime
from pathlib import Path

from .db import init_db, insert_todo, count_by_status, count_all_todos, finalize_clean, print_status, get_meta, set_meta
from .skill import sync_skill


def get_git_root() -> Path:
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        print("Error: Current directory is not a git repository.", file=sys.stderr)
        sys.exit(1)
    return Path(result.stdout.strip())


def get_default_branch(repo_root: Path) -> str:
    result = subprocess.run(
        ["git", "symbolic-ref", "refs/remotes/origin/HEAD"],
        capture_output=True, text=True, cwd=repo_root
    )
    if result.returncode == 0:
        return result.stdout.strip().rsplit("/", 1)[-1]
    return "main"


def get_current_branch(repo_root: Path) -> str:
    result = subprocess.run(
        ["git", "rev-parse", "--abbrev-ref", "HEAD"],
        capture_output=True, text=True, cwd=repo_root
    )
    return result.stdout.strip() if result.returncode == 0 else ""


def is_clean_tree(repo_root: Path) -> bool:
    result = subprocess.run(
        ["git", "status", "--porcelain"],
        capture_output=True, text=True, cwd=repo_root
    )
    return result.returncode == 0 and result.stdout.strip() == ""


def branch_exists(repo_root: Path, branch: str) -> bool:
    result = subprocess.run(
        ["git", "rev-parse", "--verify", "--quiet", f"refs/heads/{branch}"],
        capture_output=True, text=True, cwd=repo_root
    )
    return result.returncode == 0


def create_clean_branch(repo_root: Path) -> str:
    base = f"repo_clean_{datetime.now().strftime('%y%m%d')}"
    branch = base
    suffix = 2
    while branch_exists(repo_root, branch):
        branch = f"{base}_{suffix}"
        suffix += 1
    result = subprocess.run(
        ["git", "checkout", "-b", branch],
        capture_output=True, text=True, cwd=repo_root
    )
    if result.returncode != 0:
        print(f"Error creating branch: {result.stderr}", file=sys.stderr)
        sys.exit(1)
    return branch


def run_test_command(repo_root: Path, command: str) -> int:
    print(f"==> Running tests: {command}\n")
    result = subprocess.run(command, shell=True, cwd=repo_root)
    return result.returncode


def setup_claude_dir(repo_root: Path) -> Path:
    claude_dir = repo_root / ".claude"
    claude_dir.mkdir(exist_ok=True)

    gitignore = repo_root / ".gitignore"
    if gitignore.exists():
        content = gitignore.read_text(encoding="utf-8")
        if ".claude/" not in content and ".claude" not in content:
            with open(gitignore, "a", encoding="utf-8") as f:
                f.write("\n.claude/\n")
    else:
        gitignore.write_text(".claude/\n", encoding="utf-8")

    return claude_dir


def run_claude_headless(prompt: str) -> int:
    process = subprocess.Popen(
        ["claude", "--print", "--dangerously-skip-permissions", prompt],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
        encoding="utf-8",
        errors="replace",
    )
    for line in process.stdout:
        print(line, end="", flush=True)
    process.wait()
    return process.returncode


def run_claude_interactive(prompt: str) -> int:
    result = subprocess.run(["claude", "--dangerously-skip-permissions", prompt])
    return result.returncode


FILE_SIZE_LIMIT_LINES = 1900

GENERATED_PATH_SEGMENTS = ("vendor/", "node_modules/", "third_party/", "generated/", ".generated/")
GENERATED_NAME_SUFFIXES = ("_pb2.py", "_pb2_grpc.py", ".pb.go", ".g.dart", ".g.cs")
GENERATED_NAME_SUBSTRINGS = (".generated.",)
GENERATED_HEADER_MARKERS = ("code generated by", "do not edit", "auto-generated", "autogenerated")


def _is_generated_or_vendored(rel_path: str, abs_path: Path) -> bool:
    norm = rel_path.replace("\\", "/").lower()
    if any(seg in f"/{norm}" for seg in GENERATED_PATH_SEGMENTS):
        return True
    name = norm.rsplit("/", 1)[-1]
    if any(name.endswith(s) for s in GENERATED_NAME_SUFFIXES):
        return True
    if any(s in name for s in GENERATED_NAME_SUBSTRINGS):
        return True
    try:
        with abs_path.open(encoding="utf-8", errors="ignore") as f:
            head = "".join(next(f, "") for _ in range(5)).lower()
            if any(marker in head for marker in GENERATED_HEADER_MARKERS):
                return True
    except OSError:
        pass
    return False


def seed_large_files(repo_root: Path, db_path: Path) -> None:
    result = subprocess.run(
        ["git", "ls-files"],
        capture_output=True, text=True, cwd=repo_root
    )
    if result.returncode != 0:
        return

    found = 0
    skipped = 0
    for rel_path in result.stdout.splitlines():
        abs_path = repo_root / rel_path
        try:
            line_count = sum(1 for _ in abs_path.open(encoding="utf-8", errors="ignore"))
        except OSError:
            continue
        if line_count <= FILE_SIZE_LIMIT_LINES:
            continue
        if _is_generated_or_vendored(rel_path, abs_path):
            skipped += 1
            continue
        insert_todo(
            db_path,
            description=f"File is {line_count} lines — split into smaller, focused modules",
            file_path=rel_path,
            rule="file-size",
            sort_order=0,
        )
        found += 1

    if found:
        print(f"==> {found} large file(s) added to todo list.")
    if skipped:
        print(f"==> {skipped} large file(s) skipped (generated or vendored).")


def run_clean_loop(db_path: Path) -> None:
    initial = count_by_status(db_path, "pending") + count_by_status(db_path, "in_progress")
    cap = initial * 2
    iterations = 0
    failed_before = count_by_status(db_path, "failed")
    while iterations < cap:
        remaining = count_by_status(db_path, "pending") + count_by_status(db_path, "in_progress")
        if remaining == 0:
            return
        print(f"\n==> {remaining} item(s) remaining. Running clean... ({iterations + 1}/{cap})\n")
        run_claude_headless("use the repo-clean skill with the clean parameter")
        iterations += 1

        failed_after = count_by_status(db_path, "failed")
        if failed_after > failed_before:
            print(f"\n!! New failure(s) detected. Launching summarize to investigate or unblock...\n")
            run_claude_interactive("use the repo-clean skill with the summarize parameter")
        failed_before = failed_after
    print(f"\n!! Iteration cap ({cap}) reached with items still pending. Run `repo-clean` again or review the todo list.")


def run_init(db_path: Path) -> None:
    print("\n==> Running repo initialization (one-time detection of test/lint/build commands)...\n")
    run_claude_headless("use the repo-clean skill with the init parameter")


def ensure_init(db_path: Path) -> None:
    if get_meta(db_path, "init_done") != "1":
        run_init(db_path)


def run_fresh_start(repo_root: Path, db_path: Path) -> bool:
    ensure_init(db_path)

    default = get_default_branch(repo_root)
    current = get_current_branch(repo_root)
    if current != default:
        print(f"Error: Must run on default branch '{default}' (currently on '{current}').", file=sys.stderr)
        sys.exit(1)
    if not is_clean_tree(repo_root):
        print("Error: Working tree has uncommitted or untracked changes. Commit, stash, or clean them before running repo-clean.", file=sys.stderr)
        sys.exit(1)

    test_cmd = (get_meta(db_path, "test_command") or "").strip()
    if test_cmd:
        rc = run_test_command(repo_root, test_cmd)
        if rc != 0:
            print(f"\n!! Pre-flight tests failed (exit code {rc}). Fix tests before running repo-clean.", file=sys.stderr)
            sys.exit(1)
        print("\n✓ Pre-flight tests passed.")

    print("\n==> Running build phase...\n")
    seed_large_files(repo_root, db_path)
    run_claude_headless("use the repo-clean skill with the build parameter")

    if count_by_status(db_path, "pending") == 0:
        print("\n✓ No issues found. Repository is already clean!")
        finalize_clean(db_path)
        return False

    branch = create_clean_branch(repo_root)
    print(f"\n==> Created branch '{branch}'")
    set_meta(db_path, "clean_branch", branch)

    if test_cmd:
        insert_todo(
            db_path,
            description=f"Re-run tests and verify all pass: {test_cmd}",
            file_path="",
            rule="test-verify",
            sort_order=99999,
        )

    return True


def run_full(repo_root: Path, db_path: Path) -> None:
    if count_all_todos(db_path) == 0:
        if not run_fresh_start(repo_root, db_path):
            return

    print("\n==> Build complete. Starting interactive review...\n")
    print("    Exit the review session to begin cleaning.\n")
    run_claude_interactive("use the repo-clean skill with the summarize parameter")

    run_clean_loop(db_path)

    failed = count_by_status(db_path, "failed")
    if failed:
        print(f"\n!! {failed} item(s) failed. Review them in the summary before finalizing.")

    print("\n==> All pending items processed. Starting interactive summary...\n")
    run_claude_interactive("use the repo-clean skill with the summarize parameter")

    answer = input("\nMark repository as clean and clear todo list? (y/n): ").strip().lower()
    if answer != "y":
        print("Run repo-clean again to continue cleaning.")
        return

    all_complete = (
        count_by_status(db_path, "pending") == 0
        and count_by_status(db_path, "in_progress") == 0
        and count_by_status(db_path, "failed") == 0
        and count_by_status(db_path, "skipped") == 0
        and count_all_todos(db_path) > 0
    )

    if all_complete:
        print("\n==> All items completed. Launching /source-control to update docs, commit, push, and open a PR...\n")
        run_claude_interactive("use the source-control skill to update any needed documentation, then commit, push, and open a PR for this repo-clean branch")
    else:
        print("\n==> Skipping auto-PR — not all items completed. Push and open a PR manually if desired.")

    finalize_clean(db_path)


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="repo-clean",
        description="AI-powered repository cleanup using Claude Code",
    )
    parser.add_argument(
        "command",
        nargs="?",
        choices=["init", "build", "clean", "status"],
        help="init: detect test/lint/build commands (one-time) | build: analyze repo and create todo list | clean: run clean loop | status: show current state",
    )
    args = parser.parse_args()

    sync_skill()

    if args.command == "status":
        repo_root = get_git_root()
        db_path = repo_root / ".claude" / "repo_clean.db"
        print_status(db_path)
        return

    repo_root = get_git_root()
    claude_dir = setup_claude_dir(repo_root)
    db_path = claude_dir / "repo_clean.db"
    init_db(db_path)

    if args.command == "init":
        run_init(db_path)
    elif args.command == "build":
        seed_large_files(repo_root, db_path)
        run_claude_headless("use the repo-clean skill with the build parameter")
    elif args.command == "clean":
        run_clean_loop(db_path)
    else:
        run_full(repo_root, db_path)


if __name__ == "__main__":
    main()
