import sqlite3
import subprocess
from datetime import datetime, timezone

import pytest

from repo_clean.db import count_all_todos, count_by_status, get_meta, init_db
from repo_clean.main import (
    _is_generated_or_vendored,
    branch_exists,
    detect_nav_artifacts,
    ensure_scaffold,
    get_current_branch,
    is_clean_tree,
    run_clean_loop,
    run_full,
    run_scaffold,
    seed_large_files,
    setup_repo_clean_dir,
)


def _seed_todo(db_path, status="pending", sort_order=0, file_path="x.py", rule="comments"):
    now = datetime.now(timezone.utc).isoformat()
    conn = sqlite3.connect(db_path)
    conn.execute(
        "INSERT INTO todos (sort_order, description, file_path, rule, status, created_at, updated_at)"
        " VALUES (?, ?, ?, ?, ?, ?, ?)",
        (sort_order, f"{rule} on {file_path}", file_path, rule, status, now, now),
    )
    conn.commit()
    conn.close()


def _set_status(db_path, where_status, new_status):
    conn = sqlite3.connect(db_path)
    conn.execute(
        "UPDATE todos SET status=? WHERE id=(SELECT MIN(id) FROM todos WHERE status=?)",
        (new_status, where_status),
    )
    conn.commit()
    conn.close()


@pytest.mark.parametrize("rel_path", [
    "vendor/foo.py",
    "node_modules/pkg/index.js",
    "third_party/lib.go",
    "src/generated/api.py",
    "api_pb2.py",
    "service_pb2_grpc.py",
    "model.g.dart",
    "thing.generated.ts",
])
def test_is_generated_by_path(tmp_path, rel_path):
    abs_path = tmp_path / rel_path
    abs_path.parent.mkdir(parents=True, exist_ok=True)
    abs_path.write_text("x\n", encoding="utf-8")
    assert _is_generated_or_vendored(rel_path, abs_path) is True


def test_is_generated_by_header(tmp_path):
    f = tmp_path / "regular.py"
    f.write_text("# Code generated by tool; DO NOT EDIT.\nprint(1)\n", encoding="utf-8")
    assert _is_generated_or_vendored("regular.py", f) is True


def test_is_not_generated(tmp_path):
    f = tmp_path / "src/real.py"
    f.parent.mkdir(parents=True)
    f.write_text("def x(): return 1\n", encoding="utf-8")
    assert _is_generated_or_vendored("src/real.py", f) is False


def test_setup_repo_clean_dir_creates_dir_and_gitignore(tmp_path):
    state_dir = setup_repo_clean_dir(tmp_path)
    assert state_dir == tmp_path / ".repo-clean"
    assert state_dir.is_dir()
    assert ".repo-clean/" in (tmp_path / ".gitignore").read_text(encoding="utf-8")


def test_setup_repo_clean_dir_appends_to_existing_gitignore(tmp_path):
    (tmp_path / ".gitignore").write_text("*.log\n", encoding="utf-8")
    setup_repo_clean_dir(tmp_path)
    content = (tmp_path / ".gitignore").read_text(encoding="utf-8")
    assert "*.log" in content
    assert ".repo-clean/" in content


def test_setup_repo_clean_dir_skips_gitignore_when_already_present(tmp_path):
    (tmp_path / ".gitignore").write_text("build/\n.repo-clean/\n", encoding="utf-8")
    setup_repo_clean_dir(tmp_path)
    assert (tmp_path / ".gitignore").read_text(encoding="utf-8").count(".repo-clean/") == 1


def test_setup_repo_clean_dir_migrates_legacy_db(tmp_path):
    legacy = tmp_path / ".claude"
    legacy.mkdir()
    legacy_db = legacy / "repo_clean.db"
    legacy_db.write_bytes(b"legacy content")

    state_dir = setup_repo_clean_dir(tmp_path)

    assert (state_dir / "repo_clean.db").read_bytes() == b"legacy content"
    assert not legacy_db.exists()


def test_setup_repo_clean_dir_does_not_overwrite_existing_new_db(tmp_path):
    legacy = tmp_path / ".claude"
    legacy.mkdir()
    (legacy / "repo_clean.db").write_bytes(b"legacy content")
    state_dir_pre = tmp_path / ".repo-clean"
    state_dir_pre.mkdir()
    (state_dir_pre / "repo_clean.db").write_bytes(b"new content")

    state_dir = setup_repo_clean_dir(tmp_path)

    assert (state_dir / "repo_clean.db").read_bytes() == b"new content"
    assert (legacy / "repo_clean.db").exists()  # legacy left in place


def test_seed_large_files_flags_oversize_file(git_repo):
    big = git_repo / "big.py"
    big.write_text("x = 1\n" * 2000, encoding="utf-8")
    subprocess.run(["git", "add", "."], cwd=git_repo, check=True, capture_output=True)
    subprocess.run(["git", "commit", "-m", "big"], cwd=git_repo, check=True, capture_output=True)

    db = git_repo / "test.db"
    init_db(db)
    seed_large_files(git_repo, db)
    assert count_all_todos(db) == 1


def test_seed_large_files_skips_generated(git_repo):
    gen = git_repo / "api_pb2.py"
    gen.write_text("x = 1\n" * 2000, encoding="utf-8")
    subprocess.run(["git", "add", "."], cwd=git_repo, check=True, capture_output=True)
    subprocess.run(["git", "commit", "-m", "gen"], cwd=git_repo, check=True, capture_output=True)

    db = git_repo / "test.db"
    init_db(db)
    seed_large_files(git_repo, db)
    assert count_all_todos(db) == 0


def test_seed_large_files_ignores_small_files(git_repo):
    db = git_repo / "test.db"
    init_db(db)
    seed_large_files(git_repo, db)
    assert count_all_todos(db) == 0


def test_branch_and_tree_helpers(git_repo, monkeypatch):
    monkeypatch.chdir(git_repo)
    assert is_clean_tree(git_repo) is True
    assert get_current_branch(git_repo) == "main"
    assert branch_exists(git_repo, "main") is True
    assert branch_exists(git_repo, "nope") is False

    (git_repo / "new.txt").write_text("x\n", encoding="utf-8")
    assert is_clean_tree(git_repo) is False


def test_run_clean_loop_noop_when_empty(tmp_path, monkeypatch, capsys):
    db = tmp_path / "test.db"
    init_db(db)
    monkeypatch.setattr("repo_clean.main.run_claude_headless", lambda p: pytest.fail("should not be called"))
    run_clean_loop(db)
    assert "remaining" not in capsys.readouterr().out


def test_run_clean_loop_iteration_cap(tmp_path, monkeypatch, capsys):
    db = tmp_path / "test.db"
    init_db(db)
    _seed_todo(db)

    calls = []
    monkeypatch.setattr("repo_clean.main.run_claude_headless", lambda p: calls.append(p) or 0)

    run_clean_loop(db)

    assert len(calls) == 2  # cap = initial (1) * 2
    assert "Iteration cap (2) reached" in capsys.readouterr().out
    assert count_by_status(db, "pending") == 1


def test_run_clean_loop_completes_work_and_exits(tmp_path, monkeypatch):
    db = tmp_path / "test.db"
    init_db(db)
    _seed_todo(db, file_path="a.py")
    _seed_todo(db, file_path="b.py", sort_order=1)

    def fake_headless(prompt):
        _set_status(db, "pending", "complete")
        return 0

    monkeypatch.setattr("repo_clean.main.run_claude_headless", fake_headless)

    run_clean_loop(db)

    assert count_by_status(db, "complete") == 2
    assert count_by_status(db, "pending") == 0


def test_run_clean_loop_triggers_summarize_on_new_failure(tmp_path, monkeypatch):
    db = tmp_path / "test.db"
    init_db(db)
    _seed_todo(db)

    def fake_headless(prompt):
        _set_status(db, "pending", "failed")
        return 0

    interactive = []
    monkeypatch.setattr("repo_clean.main.run_claude_headless", fake_headless)
    monkeypatch.setattr(
        "repo_clean.main.run_claude_interactive",
        lambda p: interactive.append(p) or 0,
    )

    run_clean_loop(db)

    assert len(interactive) == 1
    assert "summarize" in interactive[0]


def test_run_clean_loop_no_summarize_when_failed_count_unchanged(tmp_path, monkeypatch):
    db = tmp_path / "test.db"
    init_db(db)
    _seed_todo(db, status="failed")
    _seed_todo(db, file_path="b.py", sort_order=1)

    def fake_headless(prompt):
        _set_status(db, "pending", "complete")
        return 0

    interactive = []
    monkeypatch.setattr("repo_clean.main.run_claude_headless", fake_headless)
    monkeypatch.setattr(
        "repo_clean.main.run_claude_interactive",
        lambda p: interactive.append(p) or 0,
    )

    run_clean_loop(db)

    assert interactive == []


def _run_full_setup(git_repo, monkeypatch):
    db = git_repo / ".repo-clean" / "repo_clean.db"
    db.parent.mkdir()
    init_db(db)
    monkeypatch.chdir(git_repo)
    return db


def test_run_full_exits_when_fresh_start_returns_false(git_repo, monkeypatch):
    db = _run_full_setup(git_repo, monkeypatch)
    monkeypatch.setattr("repo_clean.main.run_fresh_start", lambda r, d: False)
    calls = []
    monkeypatch.setattr("repo_clean.main.run_claude_interactive", lambda p: calls.append(p) or 0)
    monkeypatch.setattr("repo_clean.main.run_claude_headless", lambda p: 0)

    run_full(git_repo, db)

    assert calls == []


def test_run_full_source_control_when_all_complete(git_repo, monkeypatch):
    db = _run_full_setup(git_repo, monkeypatch)
    _seed_todo(db, status="complete")

    calls = []
    monkeypatch.setattr("repo_clean.main.run_claude_interactive", lambda p: calls.append(p) or 0)
    monkeypatch.setattr("repo_clean.main.run_claude_headless", lambda p: 0)
    monkeypatch.setattr("builtins.input", lambda _: "y")

    run_full(git_repo, db)

    assert any("source-control" in p for p in calls)
    assert get_meta(db, "last_clean_commit")  # finalize ran


def test_run_full_skips_source_control_when_items_failed(git_repo, monkeypatch, capsys):
    db = _run_full_setup(git_repo, monkeypatch)
    _seed_todo(db, status="complete", file_path="a.py")
    _seed_todo(db, status="failed", file_path="b.py", sort_order=1)

    calls = []
    monkeypatch.setattr("repo_clean.main.run_claude_interactive", lambda p: calls.append(p) or 0)
    monkeypatch.setattr("repo_clean.main.run_claude_headless", lambda p: 0)
    monkeypatch.setattr("builtins.input", lambda _: "y")

    run_full(git_repo, db)

    assert not any("source-control" in p for p in calls)
    assert "Skipping auto-PR" in capsys.readouterr().out
    assert get_meta(db, "last_clean_commit")  # finalize still ran


def test_run_full_user_declines_finalize(git_repo, monkeypatch, capsys):
    db = _run_full_setup(git_repo, monkeypatch)
    _seed_todo(db, status="complete")

    calls = []
    monkeypatch.setattr("repo_clean.main.run_claude_interactive", lambda p: calls.append(p) or 0)
    monkeypatch.setattr("repo_clean.main.run_claude_headless", lambda p: 0)
    monkeypatch.setattr("builtins.input", lambda _: "n")

    run_full(git_repo, db)

    assert not any("source-control" in p for p in calls)
    assert "Run repo-clean again" in capsys.readouterr().out
    assert get_meta(db, "last_clean_commit") is None  # finalize did NOT run
    assert count_all_todos(db) == 1  # todos preserved


# ---- detect_nav_artifacts ----


def test_detect_nav_artifacts_empty(tmp_path):
    assert detect_nav_artifacts(tmp_path) == []


def test_detect_nav_artifacts_finds_root_markdown(tmp_path):
    (tmp_path / "AGENTS.md").write_text("x\n", encoding="utf-8")
    (tmp_path / "ARCHITECTURE.md").write_text("x\n", encoding="utf-8")
    found = detect_nav_artifacts(tmp_path)
    assert "AGENTS.md" in found
    assert "ARCHITECTURE.md" in found


def test_detect_nav_artifacts_finds_docs_subfolder(tmp_path):
    (tmp_path / "docs").mkdir()
    (tmp_path / "docs" / "STRUCTURE.md").write_text("x\n", encoding="utf-8")
    assert "docs/STRUCTURE.md" in detect_nav_artifacts(tmp_path)


def test_detect_nav_artifacts_finds_existing_repo_map(tmp_path):
    state_dir = tmp_path / ".repo-clean"
    state_dir.mkdir()
    (state_dir / "repo-map.md").write_text("---\n---\n", encoding="utf-8")
    assert ".repo-clean/repo-map.md" in detect_nav_artifacts(tmp_path)


def test_detect_nav_artifacts_finds_legacy_claude_repo_map(tmp_path):
    legacy = tmp_path / ".claude"
    legacy.mkdir()
    (legacy / "repo-map.md").write_text("---\n---\n", encoding="utf-8")
    assert ".claude/repo-map.md" in detect_nav_artifacts(tmp_path)


def test_detect_nav_artifacts_finds_aider_cache(tmp_path):
    cache = tmp_path / ".aider.tags.cache.v3"
    cache.mkdir()
    found = detect_nav_artifacts(tmp_path)
    assert any(f.startswith(".aider.tags.cache") for f in found)


def test_detect_nav_artifacts_finds_claude_md_nav_heading(tmp_path):
    (tmp_path / "CLAUDE.md").write_text("# Project\n\n## Project Structure\n\nstuff\n", encoding="utf-8")
    found = detect_nav_artifacts(tmp_path)
    assert any("CLAUDE.md" in f for f in found)


def test_detect_nav_artifacts_ignores_claude_md_without_nav_heading(tmp_path):
    (tmp_path / "CLAUDE.md").write_text("# Project\n\n## Install\n\nstuff\n", encoding="utf-8")
    assert detect_nav_artifacts(tmp_path) == []


# ---- run_scaffold / ensure_scaffold ----


def test_run_scaffold_enables_and_invokes_map(tmp_path, monkeypatch):
    db = tmp_path / "test.db"
    init_db(db)

    headless_calls = []
    monkeypatch.setattr("repo_clean.main.run_claude_headless", lambda p: headless_calls.append(p) or 0)
    monkeypatch.setattr("builtins.input", lambda _: "y")

    run_scaffold(tmp_path, db)

    assert get_meta(db, "repo_map_enabled") == "1"
    assert any("map" in p for p in headless_calls)


def test_run_scaffold_disables_without_invoking_map(tmp_path, monkeypatch):
    db = tmp_path / "test.db"
    init_db(db)

    headless_calls = []
    monkeypatch.setattr("repo_clean.main.run_claude_headless", lambda p: headless_calls.append(p) or 0)
    monkeypatch.setattr("builtins.input", lambda _: "n")

    run_scaffold(tmp_path, db)

    assert get_meta(db, "repo_map_enabled") == "0"
    assert headless_calls == []


def test_run_scaffold_keeps_existing_preference_when_user_declines_change(tmp_path, monkeypatch):
    db = tmp_path / "test.db"
    init_db(db)
    conn = sqlite3.connect(db)
    conn.execute("INSERT INTO meta (key, value) VALUES ('repo_map_enabled', '1')")
    conn.commit()
    conn.close()
    state_dir = tmp_path / ".repo-clean"
    state_dir.mkdir()
    (state_dir / "repo-map.md").write_text("---\n---\n", encoding="utf-8")

    headless_calls = []
    monkeypatch.setattr("repo_clean.main.run_claude_headless", lambda p: headless_calls.append(p) or 0)
    monkeypatch.setattr("builtins.input", lambda _: "n")

    run_scaffold(tmp_path, db)

    assert get_meta(db, "repo_map_enabled") == "1"  # unchanged
    assert headless_calls == []  # no regeneration


def test_run_scaffold_changes_preference_when_user_confirms(tmp_path, monkeypatch):
    db = tmp_path / "test.db"
    init_db(db)
    conn = sqlite3.connect(db)
    conn.execute("INSERT INTO meta (key, value) VALUES ('repo_map_enabled', '0')")
    conn.commit()
    conn.close()

    answers = iter(["y", "y"])  # first: change? second: enable?
    monkeypatch.setattr("builtins.input", lambda _: next(answers))
    headless_calls = []
    monkeypatch.setattr("repo_clean.main.run_claude_headless", lambda p: headless_calls.append(p) or 0)

    run_scaffold(tmp_path, db)

    assert get_meta(db, "repo_map_enabled") == "1"
    assert any("map" in p for p in headless_calls)


def test_ensure_scaffold_skips_when_already_set(tmp_path, monkeypatch):
    db = tmp_path / "test.db"
    init_db(db)
    conn = sqlite3.connect(db)
    conn.execute("INSERT INTO meta (key, value) VALUES ('repo_map_enabled', '0')")
    conn.commit()
    conn.close()

    monkeypatch.setattr("builtins.input", lambda _: pytest.fail("should not prompt"))
    monkeypatch.setattr("repo_clean.main.run_claude_headless", lambda p: pytest.fail("should not call"))

    ensure_scaffold(tmp_path, db)  # must not raise


def test_ensure_scaffold_runs_when_unset(tmp_path, monkeypatch):
    db = tmp_path / "test.db"
    init_db(db)

    monkeypatch.setattr("builtins.input", lambda _: "n")
    monkeypatch.setattr("repo_clean.main.run_claude_headless", lambda p: 0)

    ensure_scaffold(tmp_path, db)

    assert get_meta(db, "repo_map_enabled") == "0"


def test_run_scaffold_generates_when_enabled_but_file_missing(tmp_path, monkeypatch):
    db = tmp_path / "test.db"
    init_db(db)
    conn = sqlite3.connect(db)
    conn.execute("INSERT INTO meta (key, value) VALUES ('repo_map_enabled', '1')")
    conn.commit()
    conn.close()

    monkeypatch.setattr("builtins.input", lambda _: pytest.fail("should not prompt"))
    headless_calls = []
    monkeypatch.setattr("repo_clean.main.run_claude_headless", lambda p: headless_calls.append(p) or 0)

    run_scaffold(tmp_path, db)

    assert any("map" in p for p in headless_calls)
