import subprocess

import pytest

from repo_clean.db import count_all_todos, init_db
from repo_clean.main import (
    _is_generated_or_vendored,
    branch_exists,
    get_current_branch,
    is_clean_tree,
    seed_large_files,
    setup_claude_dir,
)


@pytest.mark.parametrize("rel_path", [
    "vendor/foo.py",
    "node_modules/pkg/index.js",
    "third_party/lib.go",
    "src/generated/api.py",
    "api_pb2.py",
    "service_pb2_grpc.py",
    "model.g.dart",
    "thing.generated.ts",
])
def test_is_generated_by_path(tmp_path, rel_path):
    abs_path = tmp_path / rel_path
    abs_path.parent.mkdir(parents=True, exist_ok=True)
    abs_path.write_text("x\n", encoding="utf-8")
    assert _is_generated_or_vendored(rel_path, abs_path) is True


def test_is_generated_by_header(tmp_path):
    f = tmp_path / "regular.py"
    f.write_text("# Code generated by tool; DO NOT EDIT.\nprint(1)\n", encoding="utf-8")
    assert _is_generated_or_vendored("regular.py", f) is True


def test_is_not_generated(tmp_path):
    f = tmp_path / "src/real.py"
    f.parent.mkdir(parents=True)
    f.write_text("def x(): return 1\n", encoding="utf-8")
    assert _is_generated_or_vendored("src/real.py", f) is False


def test_setup_claude_dir_creates_dir_and_gitignore(tmp_path):
    claude_dir = setup_claude_dir(tmp_path)
    assert claude_dir == tmp_path / ".claude"
    assert claude_dir.is_dir()
    assert ".claude/" in (tmp_path / ".gitignore").read_text(encoding="utf-8")


def test_setup_claude_dir_appends_to_existing_gitignore(tmp_path):
    (tmp_path / ".gitignore").write_text("*.log\n", encoding="utf-8")
    setup_claude_dir(tmp_path)
    content = (tmp_path / ".gitignore").read_text(encoding="utf-8")
    assert "*.log" in content
    assert ".claude/" in content


def test_setup_claude_dir_skips_gitignore_when_already_present(tmp_path):
    (tmp_path / ".gitignore").write_text("build/\n.claude/\n", encoding="utf-8")
    setup_claude_dir(tmp_path)
    assert (tmp_path / ".gitignore").read_text(encoding="utf-8").count(".claude") == 1


def test_seed_large_files_flags_oversize_file(git_repo):
    big = git_repo / "big.py"
    big.write_text("x = 1\n" * 2000, encoding="utf-8")
    subprocess.run(["git", "add", "."], cwd=git_repo, check=True, capture_output=True)
    subprocess.run(["git", "commit", "-m", "big"], cwd=git_repo, check=True, capture_output=True)

    db = git_repo / "test.db"
    init_db(db)
    seed_large_files(git_repo, db)
    assert count_all_todos(db) == 1


def test_seed_large_files_skips_generated(git_repo):
    gen = git_repo / "api_pb2.py"
    gen.write_text("x = 1\n" * 2000, encoding="utf-8")
    subprocess.run(["git", "add", "."], cwd=git_repo, check=True, capture_output=True)
    subprocess.run(["git", "commit", "-m", "gen"], cwd=git_repo, check=True, capture_output=True)

    db = git_repo / "test.db"
    init_db(db)
    seed_large_files(git_repo, db)
    assert count_all_todos(db) == 0


def test_seed_large_files_ignores_small_files(git_repo):
    db = git_repo / "test.db"
    init_db(db)
    seed_large_files(git_repo, db)
    assert count_all_todos(db) == 0


def test_branch_and_tree_helpers(git_repo, monkeypatch):
    monkeypatch.chdir(git_repo)
    assert is_clean_tree(git_repo) is True
    assert get_current_branch(git_repo) == "main"
    assert branch_exists(git_repo, "main") is True
    assert branch_exists(git_repo, "nope") is False

    (git_repo / "new.txt").write_text("x\n", encoding="utf-8")
    assert is_clean_tree(git_repo) is False
